### ISSUE TITLE
.env should not be included in source control

### ISSUE THREAD

**Issue by ricka** [heroku/node-js-getting-started#47]
@jonmountjoy 
Per the [12 factor app guidelines on configuration](https://12factor.net/config), there should be an explicit split between code and config.  .env files should typically be included in a .gitignore and shouldn't be contained within the codebase itself.

If needed, developers can pull different environment config into their own environment with `heroku config` on the command line to export environment variables.

**Comment by jonmountjoy** [comment]
You are correct, and it's not ideal the way I've done it.  It's like that because this code base was written to support [the tutorial](https://devcenter.heroku.com/articles/getting-started-with-nodejs), which utilizes the existing `.env` to make it easier for folk to start.

I don't like it though, it's promoting a bad practice I guess, so I'll set about fixing it there and elsewhere sometime in the future.  Thanks!

**Comment by ricka** [comment]
It looks like the first place it is used or mentioned is [on this page](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars).  Perhaps just changing the instructions to create the file?  Better yet (in my opinion) would be to show how to first create the environment variables on heroku and then show how to copy down those environment variables with `heroku config -s > .env`.  Just a thought.

**Comment by aalaap** [comment]
An alternative is to supply a `.env.example` file with placeholders and instructing the users to rename it to `.env` during the tutorial.

**Comment by kunal8411** [comment]
Yes, We can add .env.example file, I will do those changes. Thanks
